import { Leaf, ArrowLeft } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";

export default function Terms() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-emerald-50/60 via-background to-amber-50/40 dark:from-emerald-950/30 dark:via-background dark:to-amber-950/20">
      <header className="sticky top-0 z-10 bg-background/80 backdrop-blur border-b border-border/50 px-4 py-3 flex items-center gap-3">
        <Link href="/">
          <Button variant="ghost" size="sm" className="gap-1.5 text-muted-foreground hover:text-foreground">
            <ArrowLeft className="w-4 h-4" />
            Back
          </Button>
        </Link>
        <div className="flex items-center gap-2">
          <Leaf className="h-5 w-5 text-emerald-600" />
          <span className="font-bold text-lg">LawnRX</span>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-5 py-10 space-y-8">
        <div className="space-y-2">
          <h1 className="text-3xl font-bold tracking-tight">Terms &amp; Conditions</h1>
          <p className="text-sm text-muted-foreground">Effective date: April 30, 2026 · Last updated: June 26, 2026</p>
        </div>

        <Section title="1. Acceptance of Terms">
          <p>
            By accessing or using LawnRX ("the App," "we," "us," or "our"), you agree to be bound by these Terms &amp;
            Conditions ("Terms"). If you do not agree to these Terms, please do not use the App. We reserve the right to
            update these Terms at any time, and continued use of the App after such changes constitutes your acceptance
            of the revised Terms.
          </p>
        </Section>

        <Section title="2. Description of Service">
          <p>
            LawnRX is an AI-powered lawn diagnosis and care planning application. Users can upload photographs of their
            lawn, receive automated analysis, health scores, and personalized recovery plans generated by artificial
            intelligence. The App offers a free tier (limited to 2 analyses) and a paid Pro membership with unlimited
            analyses and additional features including fertilizing and care alerts.
          </p>
        </Section>

        <Section title="3. Not Professional Advice">
          <p>
            <strong>The content generated by LawnRX, including diagnoses, health scores, recovery plans, product
            suggestions, and care advice, is for informational and educational purposes only.</strong> It does not
            constitute professional agronomic, horticultural, or landscaping advice. AI-generated analysis may contain
            errors or be unsuitable for your specific lawn conditions, climate, soil type, or local regulations.
          </p>
          <p className="mt-3">
            Always consult a qualified lawn care professional, certified agronomist, or local cooperative extension
            service before applying treatments, pesticides, herbicides, or fertilizers to your lawn. LawnRX is not
            responsible for any damage to your lawn, property, or the environment arising from actions taken based on
            the App's output.
          </p>
        </Section>

        <Section title="4. User Accounts">
          <p>
            You must sign in using your Replit account to access the App. You are responsible for maintaining the
            confidentiality of your account credentials and for all activities that occur under your account. You agree
            to notify us immediately of any unauthorized use of your account.
          </p>
          <p className="mt-3">
            You must be at least 13 years of age (or the minimum digital age of consent in your jurisdiction) to use
            the App. By signing in, you represent that you meet this requirement.
          </p>
        </Section>

        <Section title="5. Photo Uploads &amp; User Content">
          <p>
            By uploading photographs or other content to LawnRX, you grant us a non-exclusive, royalty-free,
            worldwide license to store, process, and transmit that content solely for the purpose of providing the
            App's services to you. Photos uploaded for AI lawn diagnosis are transmitted to our AI provider (OpenAI)
            for analysis and are not permanently stored on our servers.
          </p>
          <p className="mt-3">
            If you choose to attach a photo to a professional service quote request using the "Get a Quote" feature,
            that photo may be shared with the matched lawn care professional to help them prepare an accurate quote.
            This sharing occurs only with your explicit consent, obtained at the time of submission.
          </p>
          <p className="mt-3">
            You represent that you own or have the rights to any content you upload, and that your content does not
            violate any applicable laws or third-party rights. Do not upload images that contain personal or sensitive
            information of others.
          </p>
        </Section>

        <Section title="6. Subscription &amp; Billing">
          <ul className="list-disc pl-5 space-y-2">
            <li>
              <strong>Free Tier:</strong> New accounts receive 2 complimentary AI analyses at no charge. After these
              are consumed, you must upgrade to continue using the analysis feature.
            </li>
            <li>
              <strong>Pro Membership:</strong> Priced at $7.99/month. Grants unlimited analyses and access to the
              Care Alerts feature. Billed monthly through Stripe. Prices are subject to change with reasonable notice.
            </li>
            <li>
              <strong>Cancellation:</strong> You may cancel your subscription at any time through the Manage Billing
              portal in the App. Cancellation takes effect at the end of the current billing period; no partial refunds
              are issued for unused time within a billing cycle.
            </li>
            <li>
              <strong>Refunds:</strong> All charges are non-refundable except where required by applicable law.
            </li>
            <li>
              Payments are processed securely by Stripe. LawnRX does not store your payment card details.
            </li>
          </ul>
        </Section>

        <Section title="7. Acceptable Use">
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 mt-2 space-y-1.5">
            <li>Use the App for any unlawful purpose or in violation of any applicable regulations.</li>
            <li>Attempt to reverse-engineer, decompile, or otherwise extract the App's source code or AI models.</li>
            <li>Upload malicious files or content designed to interfere with the App's operation.</li>
            <li>Attempt to circumvent the free analysis limit through account creation or other means.</li>
            <li>Resell, sublicense, or commercialize the App's AI-generated output without our written permission.</li>
            <li>Use automated bots or scripts to access the App in bulk.</li>
          </ul>
        </Section>

        <Section title="8. Intellectual Property">
          <p>
            All trademarks, logos, service marks, UI design, and proprietary content of LawnRX are the exclusive
            property of LawnRX and its licensors. Nothing in these Terms grants you any right to use our trademarks
            or branding without our prior written consent.
          </p>
          <p className="mt-3">
            AI-generated diagnoses and care plans are provided to you for personal, non-commercial use only. You may
            save and share your own analysis results for personal lawn care purposes.
          </p>
        </Section>

        <Section title="9. Disclaimer of Warranties">
          <p>
            THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED,
            INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR
            NON-INFRINGEMENT. We do not warrant that the App will be error-free, uninterrupted, or that AI-generated
            diagnoses will be accurate or complete.
          </p>
        </Section>

        <Section title="10. Limitation of Liability">
          <p>
            TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, LAWNRX SHALL NOT BE LIABLE FOR ANY INDIRECT,
            INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL,
            ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE APP OR RELIANCE ON ITS OUTPUT, EVEN IF WE HAVE BEEN
            ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL LIABILITY TO YOU FOR ANY CLAIM ARISING OUT OF THESE
            TERMS SHALL NOT EXCEED THE AMOUNTS YOU PAID TO US IN THE 12 MONTHS PRECEDING THE CLAIM.
          </p>
        </Section>

        <Section title="11. Privacy">
          <p>
            Your use of the App is subject to our{" "}
            <a href="/privacy" className="text-emerald-600 underline">Privacy Policy</a>, which forms part of these
            Terms. We collect account information provided through Replit authentication, photographs you upload for
            analysis, and usage data to operate and improve the service. We use industry-standard security measures to
            protect your data. We do not sell personal information to third parties and do not use your data for
            advertising purposes.
          </p>
          <p className="mt-3">
            When you submit a professional service quote request through the "Get a Quote" feature, your name, contact
            details, location, lawn information, and any attached photos may be shared with a participating local lawn
            care professional in order to fulfil your request. This sharing occurs only with your explicit consent and
            only for the requested service. Full details are in our Privacy Policy, Section 4.
          </p>
        </Section>

        <Section title="12. Third-Party Services">
          <p>
            LawnRX integrates with the following third-party services, each governed by their own terms:
          </p>
          <ul className="list-disc pl-5 mt-2 space-y-1.5">
            <li><strong>Replit</strong> — authentication and hosting platform</li>
            <li><strong>OpenAI</strong> — AI vision analysis engine</li>
            <li><strong>Stripe</strong> — payment processing</li>
            <li>
              <strong>Participating Lawn Care Professionals</strong> — independent service providers on the LawnRX
              Partners platform. Data is shared with them only when you explicitly request a service quote, as
              described in Section 5 and the Privacy Policy, Section 4.
            </li>
          </ul>
          <p className="mt-3">
            We are not responsible for the practices, service quality, or content of these third-party services or
            independent professionals. Any service agreement, quote, or work arrangement is solely between you and the
            relevant professional.
          </p>
        </Section>

        <Section title="13. Termination">
          <p>
            We reserve the right to suspend or terminate your access to the App at any time, with or without notice,
            for conduct that we believe violates these Terms or is harmful to other users, us, or third parties.
            You may delete your account at any time by contacting us. Upon termination, your right to use the App
            ceases immediately and your saved plans may be deleted.
          </p>
        </Section>

        <Section title="14. Governing Law">
          <p>
            These Terms are governed by and construed in accordance with the laws of the United States, without
            regard to conflict of law principles. Any disputes arising under these Terms shall be resolved through
            binding arbitration or in the competent courts of the applicable jurisdiction.
          </p>
        </Section>

        <Section title="15. Contact">
          <p>
            If you have questions about these Terms, please reach out through the About page in the App. We will do
            our best to respond promptly.
          </p>
        </Section>

        <div className="pt-4 border-t border-border/50 text-xs text-muted-foreground">
          © 2026 LawnRX. All rights reserved.
        </div>
      </main>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-lg font-semibold text-foreground">{title}</h2>
      <div className="text-sm text-muted-foreground leading-relaxed space-y-1">{children}</div>
    </section>
  );
}
