// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/icons/CircularGarden.tsx": () => import("../components/mockups/icons/CircularGarden.tsx"),
  "./components/mockups/icons/GrassBlades.tsx": () => import("../components/mockups/icons/GrassBlades.tsx"),
  "./components/mockups/icons/LeafRx.tsx": () => import("../components/mockups/icons/LeafRx.tsx"),
  "./components/mockups/icons/ShieldLawn.tsx": () => import("../components/mockups/icons/ShieldLawn.tsx")
};
